;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        +workspace/switch-left
        evil-change
        evil-delete
        evil-forward-char
        evil-inner-tag
        evil-insert
        evil-mc-undo-all-cursors
        evil-next-line
        evil-normal-state
        evil-previous-line
        evil-record-macro
        ))

(setq mc/cmds-to-run-once
      '(
        +workspace/switch-right
        evil-backward-word-begin
        evil-delete-backward-char-and-join
        evil-force-normal-state
        evil-forward-word-begin
        ))
