;; (package! org-trello)

;; (use-package! org-trello
;;   (add-hook 'org-trello-mode-hook
;;             (lambda ()
;;               (define-key org-trello-mode-map (kbd "C-c x v") 'org-trello-version)
;;               (define-key org-trello-mode-map (kbd "C-c x i") 'org-trello-install-key-and-token)
;;               (define-key org-trello-mode-map (kbd "C-c x I") 'org-trello-install-board-metadata)
;;               (define-key org-trello-mode-map (kbd "C-c x c") 'org-trello-sync-card)
;;               (define-key org-trello-mode-map (kbd "C-c x s") 'org-trello-sync-buffer)
;;               (define-key org-trello-mode-map (kbd "C-c x a") 'org-trello-assign-me)
;;               (define-key org-trello-mode-map (kbd "C-c x d") 'org-trello-check-setup)
;;               (define-key org-trello-mode-map (kbd "C-c x D") 'org-trello-delete-setup)
;;               (define-key org-trello-mode-map (kbd "C-c x b") 'org-trello-create-board-and-install-metadata)
;;               (define-key org-trello-mode-map (kbd "C-c x k") 'org-trello-kill-entity)
;;               (define-key org-trello-mode-map (kbd "C-c x K") 'org-trello-kill-cards)
;;               (define-key org-trello-mode-map (kbd "C-c x a") 'org-trello-archive-card)
;;               (define-key org-trello-mode-map (kbd "C-c x A") 'org-trello-archive-cards)
;;               (define-key org-trello-mode-map (kbd "C-c x j") 'org-trello-jump-to-trello-card)
;;               (define-key org-trello-mode-map (kbd "C-c x J") 'org-trello-jump-to-trello-board)
;;               (define-key org-trello-mode-map (kbd "C-c x C") 'org-trello-add-card-comments)
;;               (define-key org-trello-mode-map (kbd "C-c x o") 'org-trello-show-card-comments)
;;               (define-key org-trello-mode-map (kbd "C-c x l") 'org-trello-show-card-labels)
;;               (define-key org-trello-mode-map (kbd "C-c x u") 'org-trello-update-board-metadata)
;;               (define-key org-trello-mode-map (kbd "C-c x h") 'org-trello-help-describing-bindings)))
;;   )
